### ISSUE TITLE
0.3.1: sphinx (4.4.0) fails

### ISSUE THREAD

**Issue by kloczek** [executablebooks/sphinx-togglebutton#41]
### Describe the bug

**context**
Generate documentation using sphinx

**expectation**
It chould be possible to generate documentation.

**bug**
Sphinx fails on building docuemnation.

```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.4.0
making output directory... done
myst v0.17.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=['colon_fence'], linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], all_links_external=False, url_schemes=['http', 'https', 'mailto', 'ftp'], ref_domains=None, highlight_code_blocks=True, number_code_blocks=[], title_to_header=False, heading_anchors=None, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'], words_per_minute=200)
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 4 added, 0 changed, 0 removed
reading sources... [100%] use
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-sphinx-togglebutton.3 { use reference/index changelog } failed

Exception occurred:
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 350, in create_translator
    setattr(translator, 'visit_' + name, MethodType(visit, translator))
TypeError: first argument must be callable
The full traceback has been saved in /tmp/sphinx-err-3tjrbcij.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
```console
$ cat /tmp/sphinx-err-3tjrbcij.log
# Sphinx version: 4.4.0
# Python version: 3.8.12 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.0.3
# Last messages:
#   done
#   checking consistency...
#   done
#   writing...
#   python-sphinx-togglebutton.3 {
#   use
#   reference/index
#   changelog
#   }
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (4.4.0) from /usr/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /usr/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /usr/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/lib/python3.8/site-packages/alabaster/__init__.py
#   myst_parser (0.17.0) from /usr/lib/python3.8/site-packages/myst_parser/__init__.py
#   sphinx_design (0.0.13) from /usr/lib/python3.8/site-packages/sphinx_design/__init__.py
#   sphinx_togglebutton (0.3.1) from /home/tkloczko/rpmbuild/BUILD/sphinx-togglebutton-0.3.1/sphinx_togglebutton/__init__.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/setup_command.py", line 175, in run
    app.build(force_all=self.all_files)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 337, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 291, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 358, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.8/site-packages/sphinx/util/__init__.py", line 548, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/manpage.py", line 104, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 37, in translate
    visitor = self.builder.create_translator(self.document, self.builder)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 128, in create_translator
    return self.app.registry.create_translator(self, *args)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 350, in create_translator
    setattr(translator, 'visit_' + name, MethodType(visit, translator))
TypeError: first argument must be callable
```

### Reproduce the bug

N/A

### List your environment

```console
Package                       Version
----------------------------- -----------------
alabaster                     0.7.12
attrs                         21.4.0
Babel                         2.9.1
build                         0.7.0
charset-normalizer            2.0.12
cycler                        0.11.0
distro                        1.6.0
docutils                      0.17.1
extras                        1.0.0
fixtures                      3.0.0
fonttools                     4.31.2
gpg                           1.17.1-unknown
idna                          3.3
imagesize                     1.3.0
importlib-metadata            4.11.3
iniconfig                     1.1.1
Jinja2                        3.0.3
kiwisolver                    1.3.2
libcomps                      0.1.18
markdown-it-py                2.0.1
MarkupSafe                    2.0.1
matplotlib                    3.5.1
mdit-py-plugins               0.3.0
mdurl                         0.1.0
myst-parser                   0.17.0
numpy                         1.22.3
olefile                       0.46
packaging                     21.3
pbr                           5.8.0
pep517                        0.12.0
Pillow                        9.0.1
pip                           22.0.4
pluggy                        1.0.0
py                            1.11.0
Pygments                      2.11.2
PyGObject                     3.42.0
pyparsing                     3.0.7
pytest                        7.1.1
python-dateutil               2.8.2
pytz                          2022.1
PyYAML                        6.0
requests                      2.27.1
setuptools                    60.9.3
six                           1.16.0
snowballstemmer               2.2.0
Sphinx                        4.4.0.dev20220215
sphinx-design                 0.0.13
sphinxcontrib-applehelp       1.0.2.dev20220108
sphinxcontrib-devhelp         1.0.2.dev20220108
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1.dev20220108
sphinxcontrib-qthelp          1.0.3.dev20220108
sphinxcontrib-serializinghtml 1.1.5
testtools                     2.5.0
tomli                         2.0.1
typing_extensions             4.0.1
urllib3                       1.26.8
wheel                         0.37.1
zipp                          3.7.0
```

**Comment by Apteryks** [comment]
Hmm, I got the same error trying to build matplotlib's documentation, and it doesn't use this module; are you sure the error has to do with togglebutton?

```
]$ cat /tmp/sphinx-err-44dox1me.log
# Sphinx version: 4.5.0
# Python version: 3.9.9 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.1.1
# Last messages:
#   api/prev_api_changes/api_changes_0.63
#   api/prev_api_changes/api_changes_0.61
#   api/prev_api_changes/api_changes_0.60
#   api/prev_api_changes/api_changes_0.54.3
#   api/prev_api_changes/api_changes_0.54
#   api/prev_api_changes/api_changes_0.50
#   api/prev_api_changes/api_changes_0.42
#   api/prev_api_changes/api_changes_0.40
#   }
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (4.5.0) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (4.5.0) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (4.5.0) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.autosummary (4.5.0) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.doctest (4.5.0) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.graphviz (4.5.0) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinx/ext/graphviz.py
#   sphinx.ext.inheritance_diagram (4.5.0) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinx/ext/inheritance_diagram.py
#   sphinx.ext.intersphinx (4.5.0) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.ifconfig (4.5.0) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinx/ext/ifconfig.py
#   IPython.sphinxext.ipython_console_highlighting (unknown version) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/IPython/sphinxext/ipython_console_highlighting.py
#   IPython.sphinxext.ipython_directive (unknown version) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/IPython/sphinxext/ipython_directive.py
#   numpydoc (1.2.1) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/numpydoc/__init__.py
#   sphinx_gallery.gen_gallery (0.10.1) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinx_gallery/gen_gallery.py
#   matplotlib.sphinxext.mathmpl (unknown version) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/matplotlib/sphinxext/mathmpl.py
#   matplotlib.sphinxext.plot_directive (3.5.1) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/matplotlib/sphinxext/plot_directive.py
#   sphinxext.custom_roles (unknown version) from /tmp/guix-build-python-matplotlib-documentation-3.5.1.drv-0/matplotlib-3.5.1/doc/sphinxext/custom_roles.py
#   sphinxext.github (unknown version) from /tmp/guix-build-python-matplotlib-documentation-3.5.1.drv-0/matplotlib-3.5.1/doc/sphinxext/github.py
#   sphinxext.math_symbol_table (unknown version) from /tmp/guix-build-python-matplotlib-documentation-3.5.1.drv-0/matplotlib-3.5.1/doc/sphinxext/math_symbol_table.py
#   sphinxext.missing_references (unknown version) from /tmp/guix-build-python-matplotlib-documentation-3.5.1.drv-0/matplotlib-3.5.1/doc/sphinxext/missing_references.py
#   sphinxext.mock_gui_toolkits (unknown version) from /tmp/guix-build-python-matplotlib-documentation-3.5.1.drv-0/matplotlib-3.5.1/doc/sphinxext/mock_gui_toolkits.py
#   sphinxext.skip_deprecated (unknown version) from /tmp/guix-build-python-matplotlib-documentation-3.5.1.drv-0/matplotlib-3.5.1/doc/sphinxext/skip_deprecated.py
#   sphinxext.redirect_from (unknown version) from /tmp/guix-build-python-matplotlib-documentation-3.5.1.drv-0/matplotlib-3.5.1/doc/sphinxext/redirect_from.py
#   sphinx_copybutton (0.5.0) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinx_copybutton/__init__.py
#   sphinx_panels (0.6.0) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinx_panels/__init__.py
#   sphinx.ext.linkcode (4.5.0) from /gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinx/ext/linkcode.py
Traceback (most recent call last):
  File "/gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinx/application.py", line 330, in build
    self.builder.build_update()
  File "/gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 283, in build_update
    self.build(['__all__'], to_build)
  File "/gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 350, in build
    self.write(docnames, list(updated_docnames), method)
  File "/gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinx/util/__init__.py", line 540, in wrapper
    return f(*args, **kwargs)
  File "/gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinx/builders/manpage.py", line 93, in write
    docwriter.write(largetree, destination)
  File "/gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinx/writers/manpage.py", line 29, in translate
    visitor = self.builder.create_translator(self.document, self.builder)
  File "/gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 120, in create_translator
    return self.app.registry.create_translator(self, *args)
  File "/gnu/store/pzgf3pbgpbnjxhwccmmp2k178jbf7lc1-profile/lib/python3.9/site-packages/sphinx/registry.py", line 342, in create_translator
    setattr(translator, 'visit_' + name, MethodType(visit, translator))
TypeError: first argument must be callable
```

**Comment by Apteryks** [comment]
@kloczek Looks like this must be this issue that you later reported against sphinx-panels, right (https://github.com/executablebooks/sphinx-panels/issues/74) ? If so, feel free to close this one.

**Comment by delameter** [comment]
Confirm that bug exists.

I made a workaround in my Makefile -- just comment out line with package in a config file using `sed`, then build man pages and uncomment it back afterwards, but "ugly" is the only word that comes to mind when I'm thinking about this approach *shudders*

**Comment by choldgraf** [comment]
I believe this one was due to using `sphinx-panels` instead of `sphinx-design`, but "panels" is going to be deprecated anyway so I think we'll close this one.
